appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: dYQA6BNp+fEw9qj8HeM0/xVz8sC8Te4Bn5+j0Ut9lILSUFShgvW5u7snldDk/YdFZrNGrk7ENZVLV/iPuJIvL5rMQ+nUeOKkuRM0oCmm/rTPV67eLPRrxHE6k9XjQ27ffrkznsOYupCwB159B/E/sO1kgp9DijcN7W4umLuZTFGroZAxMLXJ46RFFiFtOFrmTaTqqI46glaP+xAwXpUzL2vm2BmoEGqCK+fjJ8pUOgw2IeWDdHic5F8srlb26Dcy7vbSH7b4X+jhKPEBm9Y9OQK7WHxB6rZjbLUSuFilyL54YmYLuO7RnJENbOog/l5eVU+Y+5L9AsrO0fst7vgQ8BZunqnR9tds83dzrCmqFz+hjPG+7iW6d03ZAdbiuzyeMtlhjsNLkJ7GPwe2y0UwBRdOuOvWYo8b5WTYbwdCzhRB2wghqoCt1Upvfxtlnnw4QHPffrAtIkFr015Mm/vNXXJJ8s1WC74ByMnzWYbz5Gs1GiOG4yf/ZqKFrlnZxsYoHeu+yK5Cj/QfcLIyQds1lS5weXM0ZURUEVrwujTbPh50gr9QY+Faa8Uxz9B0SxwW5L8d6N5iGWJ8XglFyBYyJycKRgQtbZjWlfU+A1QNpdZJJLj744QUWy0TwJIyyhfuvPYcxWkLGg88X3BXWOY+E59Wccq42L2Iu/cX7tu1v3I=}
conda_forge_output_validation: true
